name: Frontend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - develop
    # paths-ignore:
    paths:
      - 'frontend/**'
      - '!**.md'
      - '.github/workflows/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow cont
  build:
    # needs: start
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
    - uses: actions/checkout@v3
    - name: Check / set env Prod
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |  
            echo "DIR=prod/" >> $GITHUB_ENV
    - name: Check / set env Dev
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: |
            echo "DIR=dev/" >> $GITHUB_ENV
            echo "CI=false" >> $GITHUB_ENV

    - name: Install sshpass
      run: |
          sudo apt-get update
          sudo apt-get install sshpass -y
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Compile Frontend
      run: |
            node -v
            npm -v
            cd frontend
            npm ci
            npm run build
            echo "chmod for js"
            chmod -R 755 ./build/static/js
    - name: Prepare Backend
      run: |
            sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} << EOF
            cd ${{ secrets.BASE_DIR_WEB }}${{env.DIR}} \
            && mkdir -p swd
            EOF
    - name: Deploy Frontend
      run: |
            sshpass -p "${{ secrets.SSH_PAS }}" scp -r -o StrictHostKeyChecking=no ./frontend/build/* ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}}:${{ secrets.BASE_DIR_WEB }}${{env.DIR}}swd/
    - name: Release Frontend
      run: |
            sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} << EOF
            cd ${{ secrets.BASE_DIR_WEB }}${{env.DIR}} \
            && rm -rf bak || echo "bak not found" \
            && mv prd bak || echo "prd not found" \
            && mv swd prd || echo "swd not found"
            EOF